-- SQL schema for CryptoTracker (MySQL)

CREATE DATABASE IF NOT EXISTS cryptotracker;
USE cryptotracker;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  email VARCHAR(255),
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(50) DEFAULT 'USER',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS portfolio (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  coin_id VARCHAR(100) NOT NULL,
  amount DECIMAL(30,10) NOT NULL,
  avg_price DECIMAL(30,10) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS news (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title TEXT,
  url TEXT,
  source VARCHAR(255),
  published_at DATETIME
);
